### ISSUE TITLE
Exception thrown: 'Microsoft.CSharp.RuntimeBinder.RuntimeBinderException' in Microsoft.CSharp.dll

### ISSUE THREAD

**Issue by polarstern** [Clarifai/clarifai-csharp#1]
Hi,
I use the following example from API Docs (Get Inputs Status):

```
public class MyClass
{   
    public static async Task Main()
    {
        var client = new ClarifaiClient("YOUR_API_KEY");
        
        await client.GetInputsStatus()
            .ExecuteAsync();
    }
}
```
running with Microsoft Visual Studio Community, version 15.5.27130.2027 (latest).

When I run `MyClass.Main()` for the first time, I get the following:
```
Exception thrown: 'Microsoft.CSharp.RuntimeBinder.RuntimeBinderException' in Microsoft.CSharp.dll
Exception thrown: 'Microsoft.CSharp.RuntimeBinder.RuntimeBinderException' in Microsoft.CSharp.dll
Exception thrown: 'Microsoft.CSharp.RuntimeBinder.RuntimeBinderException' in Microsoft.CSharp.dll
Exception thrown: 'Microsoft.CSharp.RuntimeBinder.RuntimeBinderException' in Microsoft.CSharp.dll
Exception thrown: 'Microsoft.CSharp.RuntimeBinder.RuntimeBinderException' in Microsoft.CSharp.dll
Exception thrown: 'Microsoft.CSharp.RuntimeBinder.RuntimeBinderException' in Microsoft.CSharp.dll
Exception thrown: 'Microsoft.CSharp.RuntimeBinder.RuntimeBinderException' in Microsoft.CSharp.dll
Exception thrown: 'Microsoft.CSharp.RuntimeBinder.RuntimeBinderException' in Microsoft.CSharp.dll
```
However, when I run `MyClass.Main()` again (second time etc.), this exception disappears. The same exception appears when using other methods, e.g. image prediction.

Does this exception appear directly in Clarifai API C# Client? If yes, what does it actually mean and how serious is it?

**Comment by rok-povsic** [comment]
Hi @polarstern ,

From what I can tell, these messages appear because of some internal exceptions that appear and are handled in the JSON library we use, outside of our code, . The author commented about it [here](https://github.com/JamesNK/Newtonsoft.Json/issues/352) - apparently nothing can be done about them.

Note that this only appears when you have _Just My Code_ turned off in the Debug settings. You might want to turn this on. 

![image](https://user-images.githubusercontent.com/1495233/36395152-e8278928-15b7-11e8-9428-3204d74e5bc1.png)

In any case, these messages should have no impact to the Clarifai C# library.

**Comment by polarstern** [comment]
Thank you very much!
